name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ github.sha }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - run: pnpm run build
          