name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ github.sha }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - run: pnpm run build
          